# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Activate(object):
    def setupUi(self, Activate):
        Activate.setObjectName("Activate")
        Activate.resize(480, 177)
        self.label = QtWidgets.QLabel(Activate)
        self.label.setGeometry(QtCore.QRect(10, 10, 461, 31))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.continue_button = QtWidgets.QPushButton(Activate)
        self.continue_button.setGeometry(QtCore.QRect(350, 50, 121, 32))
        self.continue_button.setObjectName("continue_button")
        self.activate_button = QtWidgets.QPushButton(Activate)
        self.activate_button.setGeometry(QtCore.QRect(350, 120, 121, 32))
        self.activate_button.setObjectName("activate_button")
        self.key = QtWidgets.QLineEdit(Activate)
        self.key.setGeometry(QtCore.QRect(10, 120, 341, 31))
        self.key.setObjectName("key")
        self.label_2 = QtWidgets.QLabel(Activate)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 461, 31))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.trial_info_label = QtWidgets.QLabel(Activate)
        self.trial_info_label.setGeometry(QtCore.QRect(10, 50, 341, 31))
        self.trial_info_label.setWordWrap(True)
        self.trial_info_label.setObjectName("trial_info_label")

        self.retranslateUi(Activate)
        QtCore.QMetaObject.connectSlotsByName(Activate)

    def retranslateUi(self, Activate):
        _translate = QtCore.QCoreApplication.translate
        Activate.setWindowTitle(_translate("Activate", "Tell My - Activate"))
        self.label.setText(_translate("Activate", "This is a trial version of Tell My. Get a key at tellmy.colten.me"))
        self.continue_button.setText(_translate("Activate", "Continue Trial"))
        self.activate_button.setText(_translate("Activate", "Activate"))
        self.key.setPlaceholderText(_translate("Activate", "XXXX-XXXX"))
        self.label_2.setText(_translate("Activate", "If you have a key, enter it below."))
        self.trial_info_label.setText(_translate("Activate", "You have n days left of your trial."))
