# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignIn(object):
    def setupUi(self, SignIn):
        SignIn.setObjectName("SignIn")
        SignIn.resize(320, 94)
        self.buttonBox = QtWidgets.QDialogButtonBox(SignIn)
        self.buttonBox.setGeometry(QtCore.QRect(230, 20, 81, 91))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.usernameLine = QtWidgets.QLineEdit(SignIn)
        self.usernameLine.setGeometry(QtCore.QRect(10, 30, 211, 21))
        self.usernameLine.setObjectName("usernameLine")
        self.passwordLine = QtWidgets.QLineEdit(SignIn)
        self.passwordLine.setGeometry(QtCore.QRect(10, 60, 211, 21))
        self.passwordLine.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.label = QtWidgets.QLabel(SignIn)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")

        self.retranslateUi(SignIn)
        self.buttonBox.accepted.connect(SignIn.accept)
        self.buttonBox.rejected.connect(SignIn.reject)
        QtCore.QMetaObject.connectSlotsByName(SignIn)

    def retranslateUi(self, SignIn):
        _translate = QtCore.QCoreApplication.translate
        SignIn.setWindowTitle(_translate("SignIn", "Tell My - iCloud Login"))
        self.usernameLine.setPlaceholderText(_translate("SignIn", "abc@xyd.com"))
        self.passwordLine.setPlaceholderText(_translate("SignIn", "password"))
        self.label.setText(_translate("SignIn", "iCloud Login"))
