# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_factor_auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TwoFactorAuth(object):
    def setupUi(self, TwoFactorAuth):
        TwoFactorAuth.setObjectName("TwoFactorAuth")
        TwoFactorAuth.resize(320, 130)
        self.buttonBox = QtWidgets.QDialogButtonBox(TwoFactorAuth)
        self.buttonBox.setGeometry(QtCore.QRect(10, 90, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(TwoFactorAuth)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(TwoFactorAuth)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 301, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(TwoFactorAuth)
        self.buttonBox.accepted.connect(TwoFactorAuth.accept)
        self.buttonBox.rejected.connect(TwoFactorAuth.reject)
        QtCore.QMetaObject.connectSlotsByName(TwoFactorAuth)

    def retranslateUi(self, TwoFactorAuth):
        _translate = QtCore.QCoreApplication.translate
        TwoFactorAuth.setWindowTitle(_translate("TwoFactorAuth", "2FA"))
        self.label.setText(_translate("TwoFactorAuth", "2-Factor Authentication required. A code was sent to your devices. Please enter it below."))
